# Generated by Django 4.1.4 on 2022-12-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('generation_time', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='images/')),
                ('user_id', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('image_pixel_size', models.IntegerField(null=True)),
                ('algorithm_name', models.CharField(max_length=100, null=True)),
                ('iterations', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
